import type { GovernanceDomain } from "@/types";

/**
 * The nine governance domain pages. Each entry drives its own dedicated
 * route at /governance-domains/[slug] via the shared domain template.
 * All narrative fields are placeholders pending Phase 2 content.
 */
export const governanceDomains: GovernanceDomain[] = [
  {
    slug: "ai-governance",
    name: "AI Governance",
    shortName: "AI Governance",
    eyebrow: "Governance Domain",
    summary: "[AI Governance — One-Line Summary Placeholder]",
    overview: "[AI Governance — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — CIO]", "[Audience Placeholder — CISO]", "[Audience Placeholder — Board]"],
    relatedEngagementSlugs: ["ai-governance-operating-model"],
    relatedInsightSlugs: ["ai-governance-board-oversight"],
    featured: true,
  },
  {
    slug: "digital-governance",
    name: "Digital Governance",
    shortName: "Digital Governance",
    eyebrow: "Governance Domain",
    summary: "[Digital Governance — One-Line Summary Placeholder]",
    overview: "[Digital Governance — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — CIO]", "[Audience Placeholder — Enterprise Leadership]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: [],
    featured: true,
  },
  {
    slug: "cyber-governance",
    name: "Cyber Governance",
    shortName: "Cyber Governance",
    eyebrow: "Governance Domain",
    summary: "[Cyber Governance — One-Line Summary Placeholder]",
    overview: "[Cyber Governance — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — CISO]", "[Audience Placeholder — Chief Risk Officer]"],
    relatedEngagementSlugs: ["ens-readiness-assessment", "pci-dss-advisory"],
    relatedInsightSlugs: [],
    featured: true,
  },
  {
    slug: "technology-risk",
    name: "Technology Risk",
    shortName: "Technology Risk",
    eyebrow: "Governance Domain",
    summary: "[Technology Risk — One-Line Summary Placeholder]",
    overview: "[Technology Risk — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — Chief Risk Officer]", "[Audience Placeholder — Board Members]"],
    relatedEngagementSlugs: ["technology-risk-assurance"],
    relatedInsightSlugs: [],
    featured: true,
  },
  {
    slug: "third-party-governance",
    name: "Third Party Governance",
    shortName: "Third Party Governance",
    eyebrow: "Governance Domain",
    summary: "[Third Party Governance — One-Line Summary Placeholder]",
    overview: "[Third Party Governance — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — Chief Compliance Officer]", "[Audience Placeholder — CISO]"],
    relatedEngagementSlugs: ["third-party-governance-framework"],
    relatedInsightSlugs: [],
    featured: false,
  },
  {
    slug: "privacy-data-governance",
    name: "Privacy & Data Governance",
    shortName: "Privacy & Data Governance",
    eyebrow: "Governance Domain",
    summary: "[Privacy & Data Governance — One-Line Summary Placeholder]",
    overview: "[Privacy & Data Governance — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — Chief Compliance Officer]", "[Audience Placeholder — Board Members]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: [],
    featured: false,
  },
  {
    slug: "dpdp-governance-readiness",
    name: "DPDP Governance & Readiness",
    shortName: "DPDP Readiness",
    eyebrow: "Governance Domain",
    summary: "[DPDP Governance & Readiness — One-Line Summary Placeholder]",
    overview: "[DPDP Governance & Readiness — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — Chief Compliance Officer]", "[Audience Placeholder — Enterprise Leadership]"],
    relatedEngagementSlugs: ["dpdp-governance-readiness-programme"],
    relatedInsightSlugs: [],
    featured: true,
  },
  {
    slug: "government-digital-governance",
    name: "Government Digital Governance",
    shortName: "Government Digital Governance",
    eyebrow: "Governance Domain",
    summary: "[Government Digital Governance — One-Line Summary Placeholder]",
    overview: "[Government Digital Governance — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — Government]", "[Audience Placeholder — Public Sector]"],
    relatedEngagementSlugs: ["government-digital-governance-programme"],
    relatedInsightSlugs: [],
    featured: false,
  },
  {
    slug: "governance-transformation",
    name: "Governance Transformation",
    shortName: "Governance Transformation",
    eyebrow: "Governance Domain",
    summary: "[Governance Transformation — One-Line Summary Placeholder]",
    overview: "[Governance Transformation — Overview Placeholder]",
    focusAreas: [
      "[Focus Area Placeholder 1]",
      "[Focus Area Placeholder 2]",
      "[Focus Area Placeholder 3]",
    ],
    whoItsFor: ["[Audience Placeholder — Enterprise Leadership]", "[Audience Placeholder — Board Members]"],
    relatedEngagementSlugs: [],
    relatedInsightSlugs: [],
    featured: false,
  },
];

export function getGovernanceDomainBySlug(slug: string) {
  return governanceDomains.find((domain) => domain.slug === slug);
}
